### ISSUE TITLE
Throws error even in the included tests

### ISSUE THREAD

**Issue by mbouclas** [mash/node-imagemagick-native#80]
i'm getting the following error both on windows and linux : 

This is the error i'm getting on linux
```
imagemagick-native$ node test

module.js:340
    throw err;
          ^
Error: Cannot find module 'imagemagick-native/test'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```

And this on windows :

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
M:\Work\myMailIs\servers\mml-manipulator\node_modules\imagemagick-native\build\Release\imagemagick.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (M:\Work\myMailIs\servers\mml-manipulator\node_modules\imagemagick-native\index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

Any ideas?

**Comment by elad** [comment]
Try `npm test`

**Comment by mbouclas** [comment]
> imagemagick-native@1.7.0 test m:\Work\testing\node-imagemagick-native
> tap test/test.js test/test.async.js test/test.streams.js test/test.trim.js

not ok test/test.js ..................................... 0/1
    Command: "c:\Program Files (x86)\nodejs\node.exe test.js"
    TAP version 13
    not ok 1 test/test.js
      ---
        exit:    1
        stderr:  |
          module.js:355
            Module._extensions[extension](this, filename);
                                         ^
          Error: The specified module could not be found.
          m:\Work\testing\node-imagemagick-native\build\Release\imagemagick.node
              at Error (native)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
              at Module.require (module.js:365:17)
              at require (module.js:384:17)
              at Object.<anonymous> (m:\Work\testing\node-imagemagick-native\index.js:2:18)
              at Module._compile (module.js:460:26)
              at Object.Module._extensions..js (module.js:478:10)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
        command: |
          "c:\Program Files (x86)\nodejs\node.exe test.js"
      ...
    
    1..1
    # tests 1
    # fail  1
    
not ok test/test.async.js ............................... 0/1
    Command: "c:\Program Files (x86)\nodejs\node.exe test.async.js"
    TAP version 13
    not ok 1 test/test.async.js
      ---
        exit:    1
        stderr:  |
          module.js:355
            Module._extensions[extension](this, filename);
                                         ^
          Error: The specified module could not be found.
          m:\Work\testing\node-imagemagick-native\build\Release\imagemagick.node
              at Error (native)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
              at Module.require (module.js:365:17)
              at require (module.js:384:17)
              at Object.<anonymous> (m:\Work\testing\node-imagemagick-native\index.js:2:18)
              at Module._compile (module.js:460:26)
              at Object.Module._extensions..js (module.js:478:10)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
        command: |
          "c:\Program Files (x86)\nodejs\node.exe test.async.js"
      ...
    
    1..1
    # tests 1
    # fail  1
    
not ok test/test.trim.js ................................ 0/1
    Command: "c:\Program Files (x86)\nodejs\node.exe test.trim.js"
    TAP version 13
    not ok 1 test/test.trim.js
      ---
        exit:    1
        stderr:  |
          module.js:355
            Module._extensions[extension](this, filename);
                                         ^
          Error: The specified module could not be found.
          m:\Work\testing\node-imagemagick-native\build\Release\imagemagick.node
              at Error (native)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
              at Module.require (module.js:365:17)
              at require (module.js:384:17)
              at Object.<anonymous> (m:\Work\testing\node-imagemagick-native\index.js:2:18)
              at Module._compile (module.js:460:26)
              at Object.Module._extensions..js (module.js:478:10)
              at Module.load (module.js:355:32)
              at Function.Module._load (module.js:310:12)
        command: |
          "c:\Program Files (x86)\nodejs\node.exe test.trim.js"
      ...
    
    1..1
    # tests 1
    # fail  1
    
total ................................................... 0/3

not ok

**Comment by elad** [comment]
Okay, I'll look into it when I get a chance. It's possible that this is due to a new node.

**Comment by mbouclas** [comment]
cheers

**Comment by bit-seq** [comment]
For Node `v0.12.4` on Windows I also experienced this errors raised by @mbouclas:
> And this on windows :
>
```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
M:\Work\myMailIs\servers\mml-manipulator\node_modules\imagemagick-native\build\Release\imagemagick.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (M:\Work\myMailIs\servers\mml-manipulator\node_modules\imagemagick-native\index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

@elad
> Okay, I'll look into it when I get a chance. It's possible that this is due to a new node.

Confirmed! With switching back to [`v0.12.0`](http://nodejs.org/dist/v0.12.0/) the installation succeeded.

**Comment by elad** [comment]
@mbouclas @bit-seq could you please try again with the master branch and a newer (4.x) node?

**Comment by radamesrf** [comment]
@elad you fixed it? I have the same problem.

**Comment by panda6412** [comment]
@elad , I also face this problem see #196 , should I downgrade the node version
