### ISSUE TITLE
imagemagick-native doesn't compile on io.js

### ISSUE THREAD

**Issue by gre** [mash/node-imagemagick-native#88]
I am able to make imagemagick-native work with Node.js.
but impossible to make it compile for io.js: I've tried both `iojs-v1.2.0` and `iojs-v1.6.4`

I'm on OS X (10.10.2)
Version: ImageMagick 6.8.9-8 Q16 x86_64 2014-10-23 http://www.imagemagick.org

```
$ cd /tmp; npm install imagemagick-native
\
> imagemagick-native@1.7.0 install /private/tmp/node_modules/imagemagick-native
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/imagemagick/src/imagemagick.o
In file included from ../src/imagemagick.cc:9:
In file included from ../src/imagemagick.h:4:
../node_modules/nan/nan.h:616:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/gre/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/imagemagick.cc:9:
In file included from ../src/imagemagick.h:4:
../node_modules/nan/nan.h:615:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:610:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1973:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/gre/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/imagemagick.cc:9:
In file included from ../src/imagemagick.h:4:
../node_modules/nan/nan.h:1974:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/gre/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/imagemagick.cc:9:
In file included from ../src/imagemagick.h:4:
../node_modules/nan/nan.h:1975:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/gre/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/imagemagick.cc:9:
In file included from ../src/imagemagick.h:4:
../node_modules/nan/nan.h:1975:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type
      'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1976:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/imagemagick/src/imagemagick.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gre/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:85:13)
gyp ERR! stack     at ChildProcess.emit (events.js:153:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/gre/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/imagemagick-native
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/gre/.nvm/versions/io.js/v1.2.0/bin/iojs" "/Users/gre/.nvm/versions/io.js/v1.2.0/bin/npm" "install" "imagemagick-native"
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! imagemagick-native@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagemagick-native@1.7.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the imagemagick-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls imagemagick-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

**Comment by elad** [comment]
A recent pull request (#79) should have fixed it. I haven't had the chance to release a new version with it yet - but I promise to do so soon! - so in the meantime you could try cloning `master` and testing that.

**Comment by gre** [comment]
It compiles!
Thanks

**Comment by doup** [comment]
@elad can you publish the io.js fixed version? :-)

**Comment by doup** [comment]
For reference: I've checked and in io.js `1.8.2` works, on `2.x` fails.
